resume/urls.py
from django.urls import path
from .import views

app_name = "resume"


urlpatterns = [
    path("resume/", views.PostListView.as_view(), name= 'posts' ),
    path("edit/", views.EditorView.as_view(), name= 'editor' ),

]

signs/urls.py
from django.urls import path
from .import views

app_name = "signs"


urlpatterns = [
    path("", views.Index.as_view(), name= 'index' )
]

taalim/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from signs import urls as signs_urls
from resume import urls as resume_urls



urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include(signs_urls, namespace='signs')),
    path("", include(resume_urls, namespace='resume')),
]

resume/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    
    topic = models.CharField( max_length=100)
    link = models.URLField()
    status = models.CharField(max_length=50)
    date = models.DateTimeField( auto_now= True )
    author = models.ForeignKey(
        User,
        on_delete= models.CASCADE,
    )
    def __str__(self):
        return self.topic


class Editor(models.Model):
    topic = models.CharField( max_length=100)
    
    sermon = models.CharField(max_length=50)
    date = models.DateTimeField( auto_now= True )

    def __str__(self):
        return self.topic

signs/models.py
from django.db import models
from django.contrib.auth.models import User




class UserProfile(models.Model):
	'''
	Our UserProfile model extends the built-in Django User Model
	'''
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	
	address = models.CharField(verbose_name="Address",max_length=100, null=True, blank=True)
	town = models.CharField(verbose_name="Town/City",max_length=100, null=True, blank=True)
	county = models.CharField(verbose_name="County",max_length=100, null=True, blank=True)


	def __str__(self):
		return f'{self.user}'

signs/forms.py
from django.forms import ModelForm
from .models import UserProfile
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms




class UserForm(UserCreationForm):
	'''
	Form that uses built-in UserCreationForm to handel user creation
	'''
	first_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Your first name..'}))
	last_name = forms.CharField(max_length=30, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Your last name..'}))
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	password1 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))
	password2 = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Confirm Password..','class':'password'}))



	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )





class AuthForm(AuthenticationForm):
	'''
	Form that uses built-in AuthenticationForm to handel user auth
	'''
	username = forms.EmailField(max_length=254, required=True,
		widget=forms.TextInput(attrs={'placeholder': '*Email..'}))
	password = forms.CharField(
		widget=forms.PasswordInput(attrs={'placeholder': '*Password..','class':'password'}))

	class Meta:
		model = User
		fields = ('username','password', )


class UserProfileForm(forms.ModelForm):
	'''
	Basic model-form for our user profile that extends Django user model.
	
	'''
	address = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	town = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	county = forms.CharField(max_length=100, required=True, widget = forms.HiddenInput())
	post_code = forms.CharField(max_length=8, required=True, widget = forms.HiddenInput())
	country = forms.CharField(max_length=40, required=True, widget = forms.HiddenInput())
	longitude = forms.CharField(max_length=50, required=True, widget = forms.HiddenInput())
	latitude = forms.CharField(max_length=50, required=True, widget = forms.HiddenInput())


	class Meta:
		model = UserProfile
		fields = ('address', 'town', 'county',
'country')

resume/views.py
from django.db import models
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from .models import Post, Editor



class Home(TemplateView):

    template_name = "home.html"
    

class PostListView(ListView):
    model = Post
    http_method_names = ["get"]
    context_object_name = "posts"
    queryset = Post.objects.all().order_by("-id")[0:30]
    template_name = "posts.html"



class EditorView(TemplateView):
    model = Editor
    template_name = "editor.html"
    http_method_names = ["get"]
    

signs/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.conf import settings
from django.http import JsonResponse
from django.views.generic.edit import FormView
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator

class Index(TemplateView):

    template_name = "homepage.html"
    
class SignUp(TemplateView):

    template_name = "homepage.html"
    










from .forms import (
	UserForm,
	UserProfileForm,
	AuthForm,
	)

result = "Error"
message = "There was an error, please try again"


class AccountView(TemplateView):
	'''
	Generic FormView with our mixin to display user account page
	'''
	template_name = "users/account.html"

	@method_decorator(login_required)
	def dispatch(self, *args, **kwargs):
		return super().dispatch(*args, **kwargs)



def profile_view(request):
	'''
	function view to allow users to update their profile
	'''
	user = request.user
	up = user.userprofile

	form = UserProfileForm(instance = up) 

	if request.is_ajax():
		form = UserProfileForm(data = request.POST, instance = up)
		if form.is_valid():
			obj = form.save()
			obj.has_profile = True
			obj.save()
			result = "Success"
			message = "Your profile has been updated"
		else:
			message = print('error ocurred in login')
		data = {'result': result, 'message': message}
		return JsonResponse(data)

	else:

		context = {'form': form}
		context['google_api_key'] = settings.GOOGLE_API_KEY
		context['base_country'] = settings.BASE_COUNTRY

		return render(request, 'users/profile.html', context)



class SignUpView(FormView):
	'''
	Generic FormView with our mixin for user sign-up with reCAPTURE security
	'''

	template_name = "users/sign_up.html"
	form_class = UserForm
	success_url = "/"

class SignInView(FormView):
	'''
	Generic FormView with our mixin for user sign-in
	'''

	template_name = "users/sign_in.html"
	form_class = AuthForm
	success_url = "/"

	




def sign_out(request):
	'''
	Basic view for user sign out
	'''
	logout(request)
	return redirect(reverse('users:sign-in'))

resume/templates/editor.html
{% extends 'base2.html' %}
{% load static %}

{% block contents %}

<div class="container bg-white  d-inline-block " style="margin-top: 10%; margin-left: 5%; width: 15%; height: 500px; border-radius: 10px;">
    <div class="d-block pt-3" style="height: 110px; border-width: 25px;">
        <div class="d-inline-block">
            <img class="pt-1" src= {% static 'resume/img/profile1.png' %} style="width: 60px; height: auto;" alt="">
            <div class="d-inline-block" >
                <b>N. SALIM</b>       
                <br>
                <p>Imam Shyorongi</p>  
            </div>  
         <hr>
        </div>
    </div>

    <div class="container shadow-sm " style="border-radius: 10px;">

        <a href="{% url 'resume:posts' %}" style="text-decoration: none; color: black;"><h5>Edit new khutba</h5></a>

        <hr>
        <li><a href="" style="text-decoration: none; color: black;">Muqqadimah &bbrktbrk;</a></li>
        <br>
        <li><a href="" style="text-decoration: none; color: black;">Add Ayyah &bbrktbrk;</a></li>
        <br>
        <li><a href="" style="text-decoration: none; color: black;">Add Hadith &bbrktbrk;</a></li>
        <br>
        <li><a href="" style="text-decoration: none; color: black;">Add Dalil &bbrktbrk;</a></li>
        <br>
        <li><a href="" style="text-decoration: none; color: black;">Make a break &bbrktbrk;</a></li>
        <br>
        <li><a href="" style="text-decoration: none; color: black;">Conclude &bbrktbrk;</a></li>
        <br>
        
       


    </div>
</div>


{% endblock contents %}

{% block body %}


<div class="container bg-light" style="position: absolute ;top: 170px ;width: 50%; height: 100%; left: 25%; border-radius: 10px; ">

    <div class="row mt-4 mx-1">

        <div class="col-md-3">

            <select id="inputState" class="form-control">
                <option selected>Choose...</option>
                <option>Ibn Mas'uud</option>
                <option>Mu aadh</option>
                <option>...</option>
                <option>...</option>
              </select>
        </div>

        
        <!-- <div class="col-md-3">

            <select class="custom-select"  id="inlineFormCustomSelectPref">
                <option selected>Choose...</option>
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
            </select>
        </div> -->


        
          
    </div>





</div>



{% endblock body %}

resume/templates/home.html
{% extends 'base2.html' %}

signs/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

<!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar-->

{% block nav %}

    <div class="home">
        <nav>
     
                <div class="logo"><img style="width: 125%;height: auto;" src= " {% static 'signs/img/loogo.png' %} " alt="logo"></div>
        
            <input class="w-25    search mt-4" style="color: white; padding-left: 15px; border-radius: 10px; background-color: #31d2f23f;" type="search" name="search" id="">
            <a class="" href="{% url 'resume:posts' %}" style="text-decoration: none; color: wheat; padding-top: 20px;">&plusb; make resume</a>
            <ul>
                <li>
                    <a id="signin" href="#">SignIn</a>
                </li>
                <li style="color: wheat;"> OR </li>
                <li>
                    <a id="signup" href="#">Register</a>
                </li>
                
            </ul>

        </nav>
    </div>

{% endblock nav %}

    <!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar-->
    <!--display display display display display display display display display display  -->
{% block body %}

    <div class="quran">
        <h4 style="padding-top: 10px"><b><a href="#">Read Qur'an In <br> Any Language</a></b></h4>
    <div class="qphoto"></div>
    </div>

    <div class="hadith">
        <h4 style="padding-top: 10px"><b><a href="#">Read Any Hadith <br> In Any Language</a></b></h4>
    <div class="hphoto"></div>
    </div>
    <div class="bar"></div>
    <div class="bar1"></div>
    <div class="bar2"></div>


{% endblock body %}


{% block contents %}
    <div class="container mt-3   the_cads">
        <br>
        <h3 style="text-align: center; color: rgba(255, 255, 255, 0.5); text-decoration: underline;">KHUT'BA OF FRIDAYS</h3>
        <br>
        <div class="row">
            <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                      <h5 class="card-title"> <b>Madda: </b> <a style="text-decoration: none;color: #31d2f2;" href="#">Al Mauti wa Al Hayaa</a></h5>
                      <h5 class="card-title"> <b>Khatwib :</b> </h5>
                      <h5 class="card-title"> <b>Date: </b> 01/10/1999 </h5>
                      <h5 class="card-title"><b>Place: </b><a style="text-decoration: none;color: #31d2f2;" href="#">location</a></h5>
                      <h5 class="card-title"> <b>Media-Status: </b> <a href="#" style="color: #31d2f2;"> Public </a> </h5>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                      <h5 class="card-title"> <b>Madda: </b> <a style="text-decoration: none;color: #31d2f2;" href="#">Al Mauti wa Al Hayaa</a></h5>
                      <h5 class="card-title"> <b>Khatwib :</b> </h5>
                      <h5 class="card-title"> <b>Date: </b> 01/10/1999 </h5>
                      <h5 class="card-title"><b>Place: </b><a style="text-decoration: none;color: #31d2f2;" href="#">location</a></h5>
                      <h5 class="card-title"> <b>Media-Status: </b> <a href="#" style="color: #31d2f2;"> Public </a> </h5>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                      <h5 class="card-title"> <b>Madda: </b> <a style="text-decoration: none;color: #31d2f2;" href="#">Al Mauti wa Al Hayaa</a></h5>
                      <h5 class="card-title"> <b>Khatwib :</b> </h5>
                      <h5 class="card-title"> <b>Date: </b> 01/10/1999 </h5>
                      <h5 class="card-title"><b>Place: </b><a style="text-decoration: none;color: #31d2f2;" href="#">location</a></h5>
                      <h5 class="card-title"> <b>Media-Status: </b> <a style="color: #31d2f2;" href="#"> Public </a> </h5>
                  </div>
                </div>
            </div>
        </div>
    <br>
    <h3 style="text-align: center; color:rgba(250, 250, 250, 0.5); text-decoration: underline;">THE DAILY DARSA</h3>
    <br>
        <div class="row">
            <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                      <h5 class="card-title"> <b>Madda: </b> <a style="text-decoration: none;color: #31d2f2;" href="#">Al Mauti wa Al Hayaa</a></h5>
                      <h5 class="card-title"> <b>Khatwib :</b> </h5>
                      <h5 class="card-title"> <b>Date: </b> 01/10/1999 </h5>
                      <h5 class="card-title"><b>Place: </b><a style="text-decoration: none;color: #31d2f2;" href="#">location</a></h5>
                      <h5 class="card-title"> <b>Media-Status: </b> <a href="#" style="color: #31d2f2;"> Public </a> </h5>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                      <h5 class="card-title"> <b>Madda: </b> <a style="text-decoration: none;color: #31d2f2;" href="#">Al Mauti wa Al Hayaa</a></h5>
                      <h5 class="card-title"> <b>Khatwib :</b> </h5>
                      <h5 class="card-title"> <b>Date: </b> 01/10/1999 </h5>
                      <h5 class="card-title"><b>Place: </b><a style="text-decoration: none;color: #31d2f2;" href="#">location</a></h5>
                      <h5 class="card-title"> <b>Media-Status: </b> <a href="#" style="color: #31d2f2;"> Public </a> </h5>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card">
                  <div class="card-body">
                      <h5 class="card-title"> <b>Madda: </b> <a style="text-decoration: none;color: #31d2f2;" href="#">Al Mauti wa Al Hayaa</a></h5>
                      <h5 class="card-title"> <b>Khatwib :</b> </h5>
                      <h5 class="card-title"> <b>Date: </b> 01/10/1999 </h5>
                      <h5 class="card-title"><b>Place: </b><a style="text-decoration: none;color: #31d2f2;" href="#">location</a></h5>
                      <h5 class="card-title"> <b>Media-Status: </b> <a href="#" style="color: #31d2f2;"> Public </a> </h5>
                  </div>
                </div>
            </div>
        </div>
    </div>


{% endblock contents %}
    

taalim/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'signs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'signs/css/main.css' %}">
    <title> {% block title %}{% endblock title %} </title>
</head>
<body>
    {% block nav %}{% endblock nav %}    
    {% block body %}{% endblock body %}
    {% block contents %}{% endblock contents %}
    {% block other %}{% endblock other %}


    <script src="{% static 'signs/js/jquery.js' %}"></script>
    <script src="{% static 'signs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'signs/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'signs/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'signs/js/main.js' %}"></script>
	<script>
        /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
    //We start indexing at one because CSRF_token is considered and input field 
    */

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username..';
    form_fields[2].placeholder='Email..';
    form_fields[3].placeholder='Enter password...';
    form_fields[4].placeholder='Re-enter Password...';


    for (var field in form_fields){	
    form_fields[field].className += ' form-control'
    }
    </script>
</body>
</html>

taalim/templates/base2.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/x-icon" href="{% static 'resume/img/favcon.png' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'signs/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'resume/css/resume.css' %}">
    <title>{% block title %}{% endblock title %}</title>
   
</head>
<body>
    

        <!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar--><!-- navbar-->
        <nav class="navtop">

            <a href="/"><img class="logo" src="{% static 'signs/img/loogo.png' %}" alt=""></a>
            <form class="form-inline d-inline-block mx-5 px-5">
                <input class="form-control mr-sm-2 my-3 px-3 mx-5 x-search" style="background-color:#70dff534 ; color:rgb(17, 56, 25) ; border-radius: 20px;" type="search" placeholder="Search" aria-label="Search">
            </form>
            <button class="btn btn-outline-success mx-5 my-2 my-sm-0 d-inline-block" style="background-color:#31d2f2 ;border-radius: 5px; border-color: transparent; " type="submit">Search</button>


            <a href=""  style="text-decoration: none;
                                position:absolute;
                                color: #31d2f2;
                                font-size: 40px;
                                font-weight: bolder;
                                right: 200px;
                                top: 10px;
                                " class="home-out">Log Out</a>
                            </nav>
                            
                            
                            
        <section>
                                
                                
                                {% block contents %}{% endblock contents %}
    
            <div class="container d-inline-block bg-light " style="width: 200px; border-radius: 15px; height: 320px; position: absolute; margin-top: 10%; right: 5%;">
                <h1 style="padding-left: 5px;" id="main">Options</h1>
                <hr>
                <ul>
                    
                    <li><a href="#" style="text-decoration: none; color: yellowgreen;">Read Quran</a></li>
                    <br>
                    <li><a href="#" style="text-decoration: none; color: yellowgreen;">Read hadith</a></li>
                    <br>
                    <li><a href="#" style=" font-weight: bold  ;text-decoration: none; color: black;">Manage Posts</a></li>
                    <br>
                    <li><a href="#" style=" font-weight: bold  ;text-decoration: none; color: rgb(12, 215, 241);">Manage Teams</a></li>
                    <br>
                    <li><a href="#" style=" font-weight: bold  ;text-decoration: none; color: rgb(5, 199, 5);">Connect Now</a></li>
                    <br>
    
                </ul>
            </div>
    
        </section>  




   
    {% block body %}{% endblock body %}



    <script src="{% static 'signs/js/jquery.js' %}"></script>
    <script src="{% static 'signs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'signs/bootstrap/js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'signs/bootstrap/js/bootstrap.min.js' %}"></script>

    <script src="{% static 'resume/js/resume.js' %}"></script>


</body>
</html>